### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by originzyf** [microjixl/marquee_text#1]
我要做一个列表的跑马灯  第一个跑一圈回到原来的位置 然后暂停  脏下一个开始  可是我没搞懂在哪判断他回到了原来的位置  您能说一下吗

**Comment by microjixl** [comment]
https://github.com/microjixl/marquee_text/blob/master/src/com/example/marquee/BulletinView.java#L100-L112

2017-03-04 11:16 GMT+08:00 originzyf <notifications@github.com>:

**Comment by microjixl** [comment]
getScrollX() >= textWidth 表示textview滚动到一行的尾部
